# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "k8sclass-tf-state"
    encrypt = true
    key     = "stage-mon/./terraform.tfstate"
    region  = "us-west-2"
  }
}
