# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "terraform_remote_state" "iam" {
  backend = "s3"
  config = {
    region = "us-west-2"
    bucket = "k8sclass-tf-state"
    key    = "iam/terraform.tfstate"
  }
}
