"""initial revision

Revision ID: 51a0ddb6060a
Revises: 
Create Date: 2022-07-08 04:02:36.069801+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51a0ddb6060a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "db_change_log",
        sa.Column("revision_id", sa.String(length=64)),
        sa.Column("migration_description", sa.String(length=64)),
        sa.Column("migration_type", sa.String(length=64)),
    )

    # ### end Alembic commands ###

    # ! DO NOT REMOVE THIS QUERY FROM MIGRATION - updates the db_change_log
    op.execute(
        """
        INSERT INTO db_change_log (revision_id, migration_description, migration_type)
        VALUES ('51a0ddb6060a', 'initial revision', 'upgrade')
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
    # ! DO NOT REMOVE THIS QUERY FROM MIGRATION - updates the db_change_log
    op.execute(
        """
        INSERT INTO db_change_log (revision_id, migration_description, migration_type)
        VALUES ('51a0ddb6060a', 'initial revision', 'downgrade')
    """
    )
